# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zyy/Desktop/MyHust

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zyy/Desktop/MyHust

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zyy/Desktop/MyHust/CMakeFiles /home/zyy/Desktop/MyHust/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zyy/Desktop/MyHust/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hust

# Build rule for target.
hust: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hust
.PHONY : hust

# fast build rule for target.
hust/fast:
	$(MAKE) -f CMakeFiles/hust.dir/build.make CMakeFiles/hust.dir/build
.PHONY : hust/fast

Ir/Attribute.o: Ir/Attribute.cpp.o

.PHONY : Ir/Attribute.o

# target to build an object file
Ir/Attribute.cpp.o:
	$(MAKE) -f CMakeFiles/hust.dir/build.make CMakeFiles/hust.dir/Ir/Attribute.cpp.o
.PHONY : Ir/Attribute.cpp.o

Ir/Attribute.i: Ir/Attribute.cpp.i

.PHONY : Ir/Attribute.i

# target to preprocess a source file
Ir/Attribute.cpp.i:
	$(MAKE) -f CMakeFiles/hust.dir/build.make CMakeFiles/hust.dir/Ir/Attribute.cpp.i
.PHONY : Ir/Attribute.cpp.i

Ir/Attribute.s: Ir/Attribute.cpp.s

.PHONY : Ir/Attribute.s

# target to generate assembly for a file
Ir/Attribute.cpp.s:
	$(MAKE) -f CMakeFiles/hust.dir/build.make CMakeFiles/hust.dir/Ir/Attribute.cpp.s
.PHONY : Ir/Attribute.cpp.s

Ir/IR.o: Ir/IR.cpp.o

.PHONY : Ir/IR.o

# target to build an object file
Ir/IR.cpp.o:
	$(MAKE) -f CMakeFiles/hust.dir/build.make CMakeFiles/hust.dir/Ir/IR.cpp.o
.PHONY : Ir/IR.cpp.o

Ir/IR.i: Ir/IR.cpp.i

.PHONY : Ir/IR.i

# target to preprocess a source file
Ir/IR.cpp.i:
	$(MAKE) -f CMakeFiles/hust.dir/build.make CMakeFiles/hust.dir/Ir/IR.cpp.i
.PHONY : Ir/IR.cpp.i

Ir/IR.s: Ir/IR.cpp.s

.PHONY : Ir/IR.s

# target to generate assembly for a file
Ir/IR.cpp.s:
	$(MAKE) -f CMakeFiles/hust.dir/build.make CMakeFiles/hust.dir/Ir/IR.cpp.s
.PHONY : Ir/IR.cpp.s

Ir/IRBuild.o: Ir/IRBuild.cpp.o

.PHONY : Ir/IRBuild.o

# target to build an object file
Ir/IRBuild.cpp.o:
	$(MAKE) -f CMakeFiles/hust.dir/build.make CMakeFiles/hust.dir/Ir/IRBuild.cpp.o
.PHONY : Ir/IRBuild.cpp.o

Ir/IRBuild.i: Ir/IRBuild.cpp.i

.PHONY : Ir/IRBuild.i

# target to preprocess a source file
Ir/IRBuild.cpp.i:
	$(MAKE) -f CMakeFiles/hust.dir/build.make CMakeFiles/hust.dir/Ir/IRBuild.cpp.i
.PHONY : Ir/IRBuild.cpp.i

Ir/IRBuild.s: Ir/IRBuild.cpp.s

.PHONY : Ir/IRBuild.s

# target to generate assembly for a file
Ir/IRBuild.cpp.s:
	$(MAKE) -f CMakeFiles/hust.dir/build.make CMakeFiles/hust.dir/Ir/IRBuild.cpp.s
.PHONY : Ir/IRBuild.cpp.s

Ir/IRItem.o: Ir/IRItem.cpp.o

.PHONY : Ir/IRItem.o

# target to build an object file
Ir/IRItem.cpp.o:
	$(MAKE) -f CMakeFiles/hust.dir/build.make CMakeFiles/hust.dir/Ir/IRItem.cpp.o
.PHONY : Ir/IRItem.cpp.o

Ir/IRItem.i: Ir/IRItem.cpp.i

.PHONY : Ir/IRItem.i

# target to preprocess a source file
Ir/IRItem.cpp.i:
	$(MAKE) -f CMakeFiles/hust.dir/build.make CMakeFiles/hust.dir/Ir/IRItem.cpp.i
.PHONY : Ir/IRItem.cpp.i

Ir/IRItem.s: Ir/IRItem.cpp.s

.PHONY : Ir/IRItem.s

# target to generate assembly for a file
Ir/IRItem.cpp.s:
	$(MAKE) -f CMakeFiles/hust.dir/build.make CMakeFiles/hust.dir/Ir/IRItem.cpp.s
.PHONY : Ir/IRItem.cpp.s

lexer/lexer.o: lexer/lexer.cpp.o

.PHONY : lexer/lexer.o

# target to build an object file
lexer/lexer.cpp.o:
	$(MAKE) -f CMakeFiles/hust.dir/build.make CMakeFiles/hust.dir/lexer/lexer.cpp.o
.PHONY : lexer/lexer.cpp.o

lexer/lexer.i: lexer/lexer.cpp.i

.PHONY : lexer/lexer.i

# target to preprocess a source file
lexer/lexer.cpp.i:
	$(MAKE) -f CMakeFiles/hust.dir/build.make CMakeFiles/hust.dir/lexer/lexer.cpp.i
.PHONY : lexer/lexer.cpp.i

lexer/lexer.s: lexer/lexer.cpp.s

.PHONY : lexer/lexer.s

# target to generate assembly for a file
lexer/lexer.cpp.s:
	$(MAKE) -f CMakeFiles/hust.dir/build.make CMakeFiles/hust.dir/lexer/lexer.cpp.s
.PHONY : lexer/lexer.cpp.s

lexer/tokenInfo.o: lexer/tokenInfo.cpp.o

.PHONY : lexer/tokenInfo.o

# target to build an object file
lexer/tokenInfo.cpp.o:
	$(MAKE) -f CMakeFiles/hust.dir/build.make CMakeFiles/hust.dir/lexer/tokenInfo.cpp.o
.PHONY : lexer/tokenInfo.cpp.o

lexer/tokenInfo.i: lexer/tokenInfo.cpp.i

.PHONY : lexer/tokenInfo.i

# target to preprocess a source file
lexer/tokenInfo.cpp.i:
	$(MAKE) -f CMakeFiles/hust.dir/build.make CMakeFiles/hust.dir/lexer/tokenInfo.cpp.i
.PHONY : lexer/tokenInfo.cpp.i

lexer/tokenInfo.s: lexer/tokenInfo.cpp.s

.PHONY : lexer/tokenInfo.s

# target to generate assembly for a file
lexer/tokenInfo.cpp.s:
	$(MAKE) -f CMakeFiles/hust.dir/build.make CMakeFiles/hust.dir/lexer/tokenInfo.cpp.s
.PHONY : lexer/tokenInfo.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/hust.dir/build.make CMakeFiles/hust.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/hust.dir/build.make CMakeFiles/hust.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/hust.dir/build.make CMakeFiles/hust.dir/main.cpp.s
.PHONY : main.cpp.s

syntax/analyse.o: syntax/analyse.cpp.o

.PHONY : syntax/analyse.o

# target to build an object file
syntax/analyse.cpp.o:
	$(MAKE) -f CMakeFiles/hust.dir/build.make CMakeFiles/hust.dir/syntax/analyse.cpp.o
.PHONY : syntax/analyse.cpp.o

syntax/analyse.i: syntax/analyse.cpp.i

.PHONY : syntax/analyse.i

# target to preprocess a source file
syntax/analyse.cpp.i:
	$(MAKE) -f CMakeFiles/hust.dir/build.make CMakeFiles/hust.dir/syntax/analyse.cpp.i
.PHONY : syntax/analyse.cpp.i

syntax/analyse.s: syntax/analyse.cpp.s

.PHONY : syntax/analyse.s

# target to generate assembly for a file
syntax/analyse.cpp.s:
	$(MAKE) -f CMakeFiles/hust.dir/build.make CMakeFiles/hust.dir/syntax/analyse.cpp.s
.PHONY : syntax/analyse.cpp.s

syntax/parseNode.o: syntax/parseNode.cpp.o

.PHONY : syntax/parseNode.o

# target to build an object file
syntax/parseNode.cpp.o:
	$(MAKE) -f CMakeFiles/hust.dir/build.make CMakeFiles/hust.dir/syntax/parseNode.cpp.o
.PHONY : syntax/parseNode.cpp.o

syntax/parseNode.i: syntax/parseNode.cpp.i

.PHONY : syntax/parseNode.i

# target to preprocess a source file
syntax/parseNode.cpp.i:
	$(MAKE) -f CMakeFiles/hust.dir/build.make CMakeFiles/hust.dir/syntax/parseNode.cpp.i
.PHONY : syntax/parseNode.cpp.i

syntax/parseNode.s: syntax/parseNode.cpp.s

.PHONY : syntax/parseNode.s

# target to generate assembly for a file
syntax/parseNode.cpp.s:
	$(MAKE) -f CMakeFiles/hust.dir/build.make CMakeFiles/hust.dir/syntax/parseNode.cpp.s
.PHONY : syntax/parseNode.cpp.s

syntax/symbolTable.o: syntax/symbolTable.cpp.o

.PHONY : syntax/symbolTable.o

# target to build an object file
syntax/symbolTable.cpp.o:
	$(MAKE) -f CMakeFiles/hust.dir/build.make CMakeFiles/hust.dir/syntax/symbolTable.cpp.o
.PHONY : syntax/symbolTable.cpp.o

syntax/symbolTable.i: syntax/symbolTable.cpp.i

.PHONY : syntax/symbolTable.i

# target to preprocess a source file
syntax/symbolTable.cpp.i:
	$(MAKE) -f CMakeFiles/hust.dir/build.make CMakeFiles/hust.dir/syntax/symbolTable.cpp.i
.PHONY : syntax/symbolTable.cpp.i

syntax/symbolTable.s: syntax/symbolTable.cpp.s

.PHONY : syntax/symbolTable.s

# target to generate assembly for a file
syntax/symbolTable.cpp.s:
	$(MAKE) -f CMakeFiles/hust.dir/build.make CMakeFiles/hust.dir/syntax/symbolTable.cpp.s
.PHONY : syntax/symbolTable.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... hust"
	@echo "... edit_cache"
	@echo "... Ir/Attribute.o"
	@echo "... Ir/Attribute.i"
	@echo "... Ir/Attribute.s"
	@echo "... Ir/IR.o"
	@echo "... Ir/IR.i"
	@echo "... Ir/IR.s"
	@echo "... Ir/IRBuild.o"
	@echo "... Ir/IRBuild.i"
	@echo "... Ir/IRBuild.s"
	@echo "... Ir/IRItem.o"
	@echo "... Ir/IRItem.i"
	@echo "... Ir/IRItem.s"
	@echo "... lexer/lexer.o"
	@echo "... lexer/lexer.i"
	@echo "... lexer/lexer.s"
	@echo "... lexer/tokenInfo.o"
	@echo "... lexer/tokenInfo.i"
	@echo "... lexer/tokenInfo.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... syntax/analyse.o"
	@echo "... syntax/analyse.i"
	@echo "... syntax/analyse.s"
	@echo "... syntax/parseNode.o"
	@echo "... syntax/parseNode.i"
	@echo "... syntax/parseNode.s"
	@echo "... syntax/symbolTable.o"
	@echo "... syntax/symbolTable.i"
	@echo "... syntax/symbolTable.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

